### ISSUE TITLE
Convert ActiveHighstock over to Yii2 format

### ISSUE THREAD

**Issue by acorncom** [miloschuman/yii2-highcharts#1]
Should we convert the ActiveHighstock widget over to Yii2 as well?  I don't currently have any projects that need it, so happy to wait until we've got a need ...

**Comment by miloschuman** [comment]
The SeriesDataHelper class was introduced in [v4.1.5](https://github.com/miloschuman/yii2-highcharts/releases/tag/v4.1.5) to provide much of this functionality via a simplified, chart-agnostic helper for preprocessing series data.

**Comment by acorncom** [comment]
:+1:
