### ISSUE TITLE
Setting unknown property: miloschuman\highcharts\Highcharts::options

### ISSUE THREAD

**Issue by Gl00mY-ZeiZ** [miloschuman/yii2-highcharts#15]
In @version 4.1.5 you removed:
```
public $options = [];
public $htmlOptions = [];
```
From *Highcharts* class.
So I have an error with my current configuration.
So what was a reason to delete main config properties?

**Comment by miloschuman** [comment]
Thanks for reporting, @Gl00mY-ZeiZ. There was no reason. Just a slip of the finger.
