### ISSUE TITLE
polar chart

### ISSUE THREAD

**Issue by emm888** [miloschuman/yii2-highcharts#16]
hi Milo,
I try to run polar chart, but it's shown as regular chart :(
Any suggestion?

<?php echo Highcharts::widget([
'scripts' => [
'modules/exporting',
'themes/grid-light',
],
'options' => [
'chart' => ['polar'=>true, 'type'=>'column'],

  'title' => ['text' => 'Fruit Consumption'],

  'xAxis' => [

 'categories'=> ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']

  ],

  'series' => [
     [ 'name' => 'Jane', 'data' =>  [29.9, 71.5, 106.4, 129.2, 144.0, 
     176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4]],

  ]

**Comment by miloschuman** [comment]
Thanks for reposting @emm888.

You simply need to include the `highcharts-more` script. So it would be:

```php
echo Highcharts::widget([
    'scripts' => [
        'highcharts-more',
        'modules/exporting',
        'themes/grid-light',
    ],
    'options' => [
        'chart' => ['polar' => true, 'type' => 'column'],
        'title' => ['text' => 'Fruit Consumption'],
        'xAxis' => [

            'categories' => ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
        ],
        'series' => [
            [ 'name' => 'Jane', 'data' => [29.9, 71.5, 106.4, 129.2, 144.0,
                    176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4]],
        ]
    ]
]);
```

**Comment by emm888** [comment]
thank you very much

**Comment by dadansatria** [comment]
thank you, it's helped !
