### ISSUE TITLE
Area Spline with AJAX Data and 2 series

### ISSUE THREAD

**Issue by ydakilux** [miloschuman/yii2-highcharts#20]
Hello, 

 How can we draw 2 series with AJAX data ? Can you give an example please ?
  
        Kinds regards,

                       Ydaki

**Comment by miloschuman** [comment]
In advanced cases like this, the widgets might be more of a hindrance than a help. I would just register the asset bundle and write my own JavaScript.

For instance, in your view file:
```php
<?php
    use miloschuman\highcharts\HighchartsAsset;
    HighchartsAsset::register($this)->withScripts(['highstock', 'modules/exporting']);
    $this->registerJsFile('@web/js/myChart.js', ['depends' => HighchartsAsset::className()]);
?>
<div id="container"></div>
```


and in `myChart.js`, you would have something like this (taken directly from the [Highstock compare demo](http://www.highcharts.com/stock/demo/compare)):
```js
$(function () {
    var seriesOptions = [],
        seriesCounter = 0,
        names = ['MSFT', 'AAPL', 'GOOG'],
        // create the chart when all data is loaded
        createChart = function () {

            $('#container').highcharts('StockChart', {

                rangeSelector: {
                    selected: 4
                },

                yAxis: {
                    labels: {
                        formatter: function () {
                            return (this.value > 0 ? ' + ' : '') + this.value + '%';
                        }
                    },
                    plotLines: [{
                        value: 0,
                        width: 2,
                        color: 'silver'
                    }]
                },

                plotOptions: {
                    series: {
                        compare: 'percent'
                    }
                },

                tooltip: {
                    pointFormat: '<span style="color:{series.color}">{series.name}</span>: <b>{point.y}</b> ({point.change}%)<br/>',
                    valueDecimals: 2
                },

                series: seriesOptions
            });
        };

    $.each(names, function (i, name) {

        $.getJSON('http://www.highcharts.com/samples/data/jsonp.php?filename=' + name.toLowerCase() + '-c.json&callback=?',    function (data) {

            seriesOptions[i] = {
                name: name,
                data: data
            };

            // As we're loading the data asynchronously, we don't know what order it will arrive. So
            // we keep a counter and create the chart when all the data is loaded.
            seriesCounter += 1;

            if (seriesCounter === names.length) {
                createChart();
            }
        });
    });
});
```

**Comment by ydakilux** [comment]
Thanks a lots, and a great widget by we way.

**Comment by mbshopM** [comment]
Hello,
I have a table an chart of this table but I want when I change   the table  with ajax the chart not refresh 
this is my veiw code:
`<table class="table table-hover table-advanced table-bordered" style="font-size: 10px;color: #777;" id="new_select">
                                <thead class="primary">
                                    ....
                                </thead>
                                <tbody>
                                    
                                    <?php
                                        $Totaux=0;
                                     foreach($sem as $key=>$val) { 
                                        ?>
                                     <tr>
                                        <?php for ($i=0,$j=1; $j <count($upDown) ; $i++,$j++) {  ?>
                                            <?php $Total+=$upDown[$j]; ?>
                                            <td class="lowerPadding">
                                                <?php if($upDown[$j]==0){?>
                                                    <?php echo $upDown[$j]; //$k." ". ?>
                                                <?php }else{
                                                   $percent=number_format(($upDown[$j]/$Totalprogresse)*100,2,'.','');?>
                                                <div class="progress">
                                                 <div role="progressbar" aria-valuetransitiongoal="75" class="progress-bar" style="width:<?php echo $percent; ?>%;color: currentColor;text-align: left;" aria-valuenow="75">
                                                  <span class="progressbar-back-text" style="position: absolute;margin-left: 75%;">
                                                   <?php if ($upDown[$i]<$upDown[$j]) { ?>
                                                       <i class="fa fa-caret-up" style="color: #08B940;font-size: 20px;"></i></span><?php echo $upDown[$j]; ?>
                                                   <?php }else{ ?>
                                                  <i class="fa fa-caret-down" style="color: #B51B21;font-size: 20px;"></i></span><?php echo $upDown[$j]; ?>
                                                    <?php }?>
                                                 </div>
                                                </div>
                                                 <?php  } ?>
                                            </td>
                                    </tr>
                                    <?php } ?>
                                </tbody>
                                <tfoot class="primary">
                                 ....
                               </tfoot> 
      </table>
<div class="col-md-12" >
                            <?php if (isset($sem) && !empty($sem)) { ?>
                             <div style="border: solid 1px;border-color: #f2994b !important;">
                                <?php 
                                 foreach($sem as $key=>$val) {
                                    $Categorie[]= [ $client[$key] ];
                                 }
                                foreach($sem[$semkey] as $keys=>$vals){ // Boulce sur les semaines
                                    foreach($sem as $key=>$val) { // boucle sue les categorie et ses valeurs
                                        // a chaque fois il va prendre une valeur par val
                                        foreach($val as $k=>$v){ // boucle sur le CA de chuque semaine par categorie
                                            if(strcmp($keys, $k) == 0){
                                                $elem[$keys][] =intval($v);
                                            }
                                        }
                                    }
                                    $dataProve[]=['type' => 'column','name' => $keys,'data' => $elem[$keys],];
                                }
                                   // $form=ActiveForm::begin();
                                    echo Highcharts::widget([
                                                    'scripts' => [
                                                        'modules/exporting',
                                                        'themes/grid-light',
                                                    ],
                                                    'options' => [
                                                        'title' => [
                                                            'text' => 'CA/Categorie/Semaine',
                                                        ],
                                                        'xAxis' => [
                                                            'categories' =>$Categorie,
                                                        ],
                                                        'series' => $dataProve,
                                                    ]
                                                ]);
                                  //   ActiveForm::end();
                                ?>
                            </div>
                            <?php } ?>
                    </div>
` 
how I can do that ?
