### ISSUE TITLE
Solidgauge is not working

### ISSUE THREAD

**Issue by gb5256** [miloschuman/yii2-highcharts#25]
Hi,

    'chart'=> [
                'type'=> 'solidgauge'
            ],
is not working.

**Comment by gb5256** [comment]
I found the solution.
It is not clear from the documentation, but you have to add the .js file to the script array where you also mention the highcharts-more. See below example, the second line is then loading the solid-gauge.js.

    'highcharts-more', // enables supplementary chart types (gauge, arearange, columnrange, etc.)
    'modules/solid-gauge',
    'modules/exporting', // adds Exporting button/menu to chart
    'themes/gray'        // applies global 'grid' theme to all charts

Perhaps this can be added to the offical documention.

gb5256

**Comment by leodstar93** [comment]
Highcharts::widget([
                                'scripts' => [
                                    'highcharts-more', // enables supplementary chart types (gauge, arearange, columnrange, etc.)
                                    'modules/solid-gauge',
                                    'modules/exporting',
                                    'themes/grid-light',
                                ],
                                'options' => [
                                         ....
                                 ]
                           ]
