### ISSUE TITLE
themes

### ISSUE THREAD

**Issue by gb5256** [miloschuman/yii2-highcharts#26]
Hi,
Is there a way to allow a custom theme?

thanks,
gb5256

**Comment by miloschuman** [comment]
Yes. Just include your custom theme file in the view.

```php
$this->registerJsFile('/path/to/my-custom-theme.js', [
    'depends' => 'miloschuman\highcharts\HighchartsAsset'
]);
```

The `depends` option ensures that the main Highcharts scripts get loaded first.
