### ISSUE TITLE
instead of an array of values

### ISSUE THREAD

**Issue by Zdeshniy89** [miloschuman/yii2-highcharts#28]
In example: ['name' => 'Jane', 'data' => [1, 0, 4]],
But if you replace it: ['name' => 'Jane', 'data' => $array],
where $array = [1, 0, 4];
then the schedule is not built. Why?

**Comment by miloschuman** [comment]
That scenario should work fine. I have no trouble when replacing the array literals with array variables in my examples. Double check that your `$array` variable contains the values you expect and that nothing else is breaking your code.

**Comment by hendrasyp** [comment]
Hi milo, I have same trouble, can you help me at this link ? 
[Data Series Not Showing] (http://stackoverflow.com/questions/34427691/yii2-highchart-data-series-not-showing)

**Comment by miloschuman** [comment]
@hendrasyp I see that you solved your problem on StackExchange.
@Zdeshniy89 I'm assuming you solved your issue since I haven't heard back from you in a while and closing this ticket.
