### ISSUE TITLE
3d options

### ISSUE THREAD

**Issue by ajkosh** [miloschuman/yii2-highcharts#3]
i m using 3d pie chart but it is showing simple pie and when i m using options3d ,it is giving me error

**Comment by mramdhani** [comment]
how to using ActiveDataProvider and implementation in pie highcharts? give example please.

**Comment by hannes-romauch** [comment]
well, not sure this is the right place... (sorry miloschuman), but I guess the main "hurdle" is this:

e.g. Table Products

Products
----------------------
cat     |     value
----------------------
A       |       1
B       |       2
C       |       3

ActiveDataProvider returns something like this: (simplified)

[
[A,1],
[B,2],
[C,3]
]

but we need something like this:
[
[A,B,C],
[1,2,3]
]

so, we would need to "transpose" the results and break them down:
(all done in the model)(I personally prefer to write the queries in sql in this instance)
e.g.

$sql = "SELECT cat,value from Products";
$dataProvider = Products::findBySql($sql)->all();
        
$data_cat= array();
$data_value = array();

// poor mans transpose... ;-)

foreach($dataProvider as $data) {
     $data_value[]=(int)$data['value'];   //we (int) the value as most likely mysql will return a string...
     $data_cat[]=$data['cat'];
  }

// and then return this via the controller to the view
        return ['value'=>$data_value,'cat'=>$data_cat];

------

in the view one can then access the values e.g. $dataProvider['value']

----------
PS:
a more elegant transpose, useful for multi colums:
(e.g. one array of categories, x-axis, and multiple lines in a line chart)

// getting the categories
foreach($dataProvider as $data) {
     $data_cat[]=$data['cat'];
  }

// transpose result
$out = array();
   
foreach ($dataProvider as $key => $subarr) {
    	foreach ($subarr as $subkey => $subvalue) {
    		$out[$subkey][$key] = (int)$subvalue;
    	}
    }

// eliminate categories cat from data array
unset($out['cat']);
    
//making nice data array for high charts
//prepares for multiple lines of data, with a name and the value array for the json input

$test=array();
    
foreach($out as $key=>$val ) {    
    $test[]=['name'=>$key,'data'=>$val];    
};  

return ['data'=>$test,'cat'=>$data_cat];

HTH, hope not not many typos... :-)

**Comment by ajkosh** [comment]
use arraydataprovider for showing data in chart file ,use array and render to view file and use them

**Comment by mramdhani** [comment]
It's worked ! Thanks hannos-romauch :)

**Comment by hdushku** [comment]
Please provide a real example step by step from model to controller and view
thanks
