### ISSUE TITLE
Responsive

### ISSUE THREAD

**Issue by ajithfort** [miloschuman/yii2-highcharts#30]
Hi,

how can i make this chart responsive?

**Comment by miloschuman** [comment]
I think as long as you don't set a fixed size, highcharts will be responsive out of the box. My plugin is just a wrapper for the Highcharts library, so this question would be better directed to the Highsoft staff or Q&A sites such as StackExchange. Googling "highcharts responsive" turned up this result that may be of help to you.

http://stackoverflow.com/questions/33417465/highcharts-not-responsive-after-reflow

Good luck.

**Comment by ThuzarTS** [comment]
Yii2 Highchart in pie chart inside jquery resizable not working, How can i fix?
