### ISSUE TITLE
Use bower-asset

### ISSUE THREAD

**Issue by SamMousa** [miloschuman/yii2-highcharts#32]
Yii2 uses `fxp/composer-asset-plugin` for including javascript libraries.
Is there a reason you are copying the highcharts source code into your library?

It would be cleaner to just add this to your composer.json:
````
"require": {
    ...
    "bower-asset/highcharts" : "^4.2.2"
}
````

**Comment by miloschuman** [comment]
Thanks for the question, @SamMousa. Please see #13 for an explanation of why bower-asset is still not a viable option at this time. If you have any further related questions/comments, please add them to that issue.
