### ISSUE TITLE
SeriesDataHelper does only return 20 datasets

### ISSUE THREAD

**Issue by gb5256** [miloschuman/yii2-highcharts#33]
I have just noticed that the SeriesDataHelper does only return the first 20 datasets.
Is this by design?

**Comment by nlrooat** [comment]
20 is the default value for the $dataprovider. Try
`$dataProvider = new ActiveDataProvider([`
            `'query' => $query,`
            `'pagination' => false,`
            `//'pagination' => [`
            `//    'pageSize' => 20,`
            `//],`
        `]);`

false will disable pagination. Or uncomment the commented lines (and remove the other 'pagination'  entry) and change 20 to any other value you like.

**Comment by miloschuman** [comment]
Thanks for the help, @nlrooat.

**Comment by gb5256** [comment]
No, sorry to say but that is not the problem.
I am creating the array with a $query = (new \yii\db\Query()) and not with a ActiveDataProvider.
So there is no pagination used which could be set 20.
So I would like to re-open this issue.
gb5256

**Comment by miloschuman** [comment]
You're right, @gb5256. If you pass SeriesDataHelper an array, that array gets populated into an intermediate ArrayDataProvider, which has a default pageSize of 20. I'll include a fix in the next release.
