### ISSUE TITLE
 PHP Fatal Error – yii\base\ErrorException 

### ISSUE THREAD

**Issue by aryp2306** [miloschuman/yii2-highcharts#36]
Hello dear, i tried to follow your tutorial but i have problem in my code..below message error..
![error highchart](https://cloud.githubusercontent.com/assets/15117374/15416388/063d9858-1e75-11e6-8eac-1a1093a5195e.PNG)
Thank so much

**Comment by miloschuman** [comment]
You should check your `/vendor` directory to make sure the package was properly installed.

This directory should exist under your project's root directory:
`/vendor/miloschuman/yii2-highcharts-widget`

If not, please make sure `"miloschuman/yii2-highcharts-widget": "dev-master"` exists under the 'require' section of you composer.json file, and run `composer update` from your project root.

**Comment by aryp2306** [comment]
yeah,,success dear..thank so much for your help..
