### ISSUE TITLE
Show Label only on Last Value

### ISSUE THREAD

**Issue by opaniagu** [miloschuman/yii2-highcharts#39]
Hi,

I want to show value only on the last point of the serie.

I found that one solution is to add label only on last point like this:

` data: [4, 5, 2, 9, {
                dataLabels: {
                    enabled: true,
                    align: 'left',
                    x: 3,
                    verticalAlign: 'middle',
                    overflow: true,
                    crop: false,
                    format: '{series.name}'
                },` 

My problem is that data value is an array (sql) and I can not do  to add label of last point.

`'data' => $arr_val,`

Thanks in advanced.

**Comment by miloschuman** [comment]
If I understand you correctly, before creating your Highcharts  widget, you would just need to manually pop the last value from the array, insert it into a new array with label options and then append that to the original array like this.

```php
$oldLastPoint = array_pop($arr_val);
$newLastPoint = ['dataLabels' => ['enabled' => true, 'align' => 'left', 'x' => $oldLastPoint, 'verticalAlig' => 'middle', 'overflow' => true, 'crop' => false, 'format' => '{series.name}']];
$arr_val[] = $newLastPoint;
```

**Comment by opaniagu** [comment]
Thanks!

With your help found solution. Really I want show only on same point datalabel point.

```
$oldLastPoint = array_pop($arr_p);
$newLastPoint = ['y' => $oldLastPoint, 'dataLabels' => ['enabled' => true, 'align' => 'left', 'x' => 0, 'verticalAlig' => 'middle', 'overflow' => true, 'crop' => false]];
$arr_p[] = $newLastPoint;
	

```

Thaks again.
