### ISSUE TITLE
No Chart Rendered ?

### ISSUE THREAD

**Issue by zmoddynamics** [miloschuman/yii2-highcharts#44]
Hi, I'm using this code and only the title and sub-title of the chart is rendered ?
![screen shot 2016-09-03 at 1 46 32 pm](https://cloud.githubusercontent.com/assets/964005/18227008/fb66f01c-71dc-11e6-9bfa-5ba8e2b3e39e.png)

`<div id="highchart-container">
    <?=Highcharts::widget([
        'options' => [
            'chart' =>  [
                'type' => 'column',
                'margin' => [60,10,40,40],
                'renderTo' => 'highchart-container'
            ],
            'title' => [
                'text' => 'Symmetrical Distribution',
                'x' => 25
            ],
            'subtitle' =>  [
                'text' => 'Fisher\'s Iris Data: Sepal Width',
                'x' => 25,
            ],
            'legend' =>  [
                'enabled' => false,
            ],
            'credits' => [
                'enabled' => false,
            ],
            'tooltip' => [

            ],
            'scripts' => [
                'highcharts-more',   // enables supplementary chart types (gauge, arearange, columnrange, etc.)
                'modules/exporting', // adds Exporting button/menu to chart
                'themes/grid'        // applies global 'grid' theme to all charts
            ],
            'plotOptions' => [
                'series' => [
                    'pointPadding' => 0,
                    'groupPadding' => 0.5,
                    'borderColor' => 'rgba(255,255,255,0.5)',
                    'color' => '#434348',
                ]
            ],
            'xAxis' => [
                'title' => [
                    'text' => 'Sepal Width (cm)'
                ]
            ],
            'yAxis' => [
                'title' => [
                    'text' => ''
                ]
            ],
            'series' => [
                'name' =>  'Distribution',
                'data' => [[2.1,4],[2.3000000000000003,7],[2.5,13],[2.7,23],[2.9000000000000004,36],[3.1,24],[3.3000000000000003,18],[3.5000000000000004,10],[3.7000000000000006,9],[3.9000000000000004,3],[4.1,2],[4.300000000000001,1]]
            ]
        ]
    ]);?>

</div>`

**Comment by miloschuman** [comment]
The series option requires an array of arrays. Just wrap your single series in another set of brackets like this:

```php
echo Highcharts::widget([
    'id' => 'highchart-container',
    'options' => [
        'chart' => [
            'type' => 'column',
            'margin' => [60, 10, 40, 40],
        ],
        'title' => [
            'text' => 'Symmetrical Distribution',
            'x' => 25
        ],
        'subtitle' => [
            'text' => 'Fisher\'s Iris Data: Sepal Width',
            'x' => 25,
        ],
        'legend' => [
            'enabled' => false,
        ],
        'credits' => [
            'enabled' => false,
        ],
        'tooltip' => [
        ],
        'scripts' => [
            'highcharts-more', // enables supplementary chart types (gauge, arearange, columnrange, etc.)
            'modules/exporting', // adds Exporting button/menu to chart
            'themes/grid'        // applies global 'grid' theme to all charts
        ],
        'plotOptions' => [
            'series' => [
                'pointPadding' => 0,
                'groupPadding' => 0.5,
                'borderColor' => 'rgba(255,255,255,0.5)',
                'color' => '#434348',
            ]
        ],
        'xAxis' => [
            'title' => [
                'text' => 'Sepal Width (cm)'
            ]
        ],
        'yAxis' => [
            'title' => [
                'text' => ''
            ]
        ],
        'series' => [
            [
                'name' => 'Distribution',
                'data' => [[2.1, 4], [2.3000000000000003, 7], [2.5, 13], [2.7, 23], [2.9000000000000004, 36], [3.1, 24], [3.3000000000000003, 18], [3.5000000000000004, 10], [3.7000000000000006, 9], [3.9000000000000004, 3], [4.1, 2], [4.300000000000001, 1]]
            ]
        ]
    ]
]);
```
You should also avoid using the 'renderTo' option directly unless you already have a container on the page with that ID. It is easier to use the 'id' property, which will first create the container and then inject the chart into it.

**Comment by zmoddynamics** [comment]
Thanks for the feedback. RenderTo has to be used here because the chart is rendered in a bootstrap modal via ajax. It doesn't work without the renderTo specified to an existing container .. At least not with the renderAjax for the view. I put in a pull request to fix the issue with rendering highcharts in bootstrap modal ..
