### ISSUE TITLE
Install problem 

### ISSUE THREAD

**Issue by tigrasti** [miloschuman/yii2-highcharts#45]
Problem 1
    - Conclusion: remove bower-asset/bootstrap-tagsinput 0.8.0
    - Conclusion: don't install bower-asset/bootstrap-tagsinput 0.8.0
    - Conclusion: remove bower-asset/jquery 2.2.4
    - Installation request for bower-asset/bootstrap-tagsinput (locked at 0.8.0) -> satisfiable by bower-asset/bootstrap-tagsinput[0.8.0].
    - Conclusion: don't install bower-asset/jquery 2.2.4
    - bower-asset/bootstrap-tagsinput 0.8.0 requires bower-asset/jquery ~2.1.1 -> satisfiable by bower-asset/jquery[2.1.4, 2.1.3, 2.1.2, 2.1.1].
    - Can only install one of: bower-asset/jquery[2.1.4, 2.2.4].
    - Can only install one of: bower-asset/jquery[2.1.3, 2.2.4].
    - Can only install one of: bower-asset/jquery[2.1.2, 2.2.4].
    - Can only install one of: bower-asset/jquery[2.1.1, 2.2.4].
    - Installation request for bower-asset/jquery (locked at 2.2.4) -> satisfiable by bower-asset/jquery[2.2.4].

**Comment by miloschuman** [comment]
Sorry, did you mean to post this issue to a different repo? This appears to be composer output that is entirely unrelated to the yii2-highcharts plugin.
