### ISSUE TITLE
Highcharts are not under the MIT license!!!

### ISSUE THREAD

**Issue by meyergru** [miloschuman/yii2-highcharts#47]
As I just found out, your widget packages Highcharts, which is, contrary to what you say in your licensing information, not free for commercial purposes!

**Comment by miloschuman** [comment]
You are right. I mentioned that on the [original documentation page](http://www.yiiframework.com/extension/yii2-highcharts-widget/), but somehow missed it when porting to github. Anyway, I removed the license badge from Readme.md. Thanks for the heads up.
