### ISSUE TITLE
Upgrade to 5.0.2 for a new bugfix

### ISSUE THREAD

**Issue by marekpetras** [miloschuman/yii2-highcharts#48]
Hey mate,

first, job well done on the whole extension.

Could you update to v5.0.2 though? There is a bug solved thats been bugging me in the new v5.0.0

https://github.com/highcharts/highcharts/issues/5259

My heatmaps crosshairs arent working as expected.

Cheers,
Marek

**Comment by miloschuman** [comment]
Consider it done...because it is ;-)

**Comment by marekpetras** [comment]
Thank you :)
