### ISSUE TITLE
Instalation highchart failed

### ISSUE THREAD

**Issue by mjb16** [miloschuman/yii2-highcharts#55]
i want to install highchart. when i type composer.phar require --prefer-dist miloschuman/yii2-highcharts-widget "dev-master" , an error message:
Problem 1
- Installation request for miloschuman/yii2-highcharts-widget dev-master -> satisfiable by miloschuman/yii2-highcharts-widget[dev-master].
- miloschuman/yii2-highcharts-widget dev-master requires bower-asset/highcharts 5.0.* -> no matching package found.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version accordingto your minimum-stability setting

Installation failed, reverting ./composer.json to its original content.

i use Windows 7 Professional.
Please help me

**Comment by miloschuman** [comment]
Sorry, I need to update the README file. You must first install the bower asset plugin:
```
composer global require "fxp/composer-asset-plugin:^1.2.0"
```
See the [Yii Installation Guide](http://www.yiiframework.com/doc-2.0/guide-start-installation.html#installing-from-composer) for an explanation.

**Comment by mjb16** [comment]
Thanks for fix my problem

2017-04-07 23:12 GMT+07:00 Milo Schuman <notifications@github.com>:
