### ISSUE TITLE
After installing extension, highcharts is not showing up

### ISSUE THREAD

**Issue by JananiKrishnan** [miloschuman/yii2-highcharts#60]
Hi I have installed your extension with version "version": "v5.0.2", via composer. After installed i have given your example code in my view file. But nothing is showing up. Kindly help ASAP.

Code:
 use miloschuman\highcharts\Highcharts;

echo Highcharts::widget([
   'options' => [
      'title' => ['text' => 'Fruit Consumption'],
      'xAxis' => [
         'categories' => ['Apples', 'Bananas', 'Oranges']
      ],
      'yAxis' => [
         'title' => ['text' => 'Fruit eaten']
      ],
      'series' => [
         ['name' => 'Jane', 'data' => [1, 0, 4]],
         ['name' => 'John', 'data' => [5, 7, 3]]
      ]
   ]
]);

**Comment by troo** [comment]
Hi. Have the same issue. In my case the problem was in jquery library. If it's loaded before - all fine.

**Comment by miloschuman** [comment]
@troo, thanks for the tip. You are correct; `renderPartial()` will not register the javascript files necessary to display your chart. If you are loading the page via ajax, you should use [`renderAjax()`](http://www.yiiframework.com/doc-2.0/yii-web-controller.html#renderAjax%28%29-detail) instead.

@JananiKrishnan, sorry for the late response. If this is not the issue you were experiencing (and you haven't already solved it yourself), please feel free to reopen this ticket.
