### ISSUE TITLE
Highcharts JS v7.0.1 is available

### ISSUE THREAD

**Issue by deferenty** [miloschuman/yii2-highcharts#72]
Hi!
New version of Highchars is available.
There are some bugs fixed in Highcharts v7.0.1 and it will be great if JS library will be up to date)
So there are some changes in styleMode usage, seems, it's fully compatible with 6.0.2 version.

https://www.highcharts.com/documentation/changelog

Thanks in advance and Happy New Year!

**Comment by miloschuman** [comment]
Resolved in cd248e9e84556f4e95dbfba266cda04750ddd653.
