### ISSUE TITLE
After update to 7.1.2 get error: Trying to get property 'chart' of non-object

### ISSUE THREAD

**Issue by gatons** [miloschuman/yii2-highcharts#76]
Hello, after widget update to 7.1.2 get error: Trying to get property 'chart' of non-object....

![image](https://user-images.githubusercontent.com/6638922/63513357-9efaae00-c4ee-11e9-90de-6abfce5a3bce.png)

when roll back to 7.0 version, works.

**Comment by aboptech007** [comment]
Hello,
Check this pull request #75 . It fixes this issue.

**Comment by miloschuman** [comment]
Thanks for the PR. Resolved in #75.
