### ISSUE TITLE
HighchartsAsset::register($this)->withScripts(['highstock']); results with error 16

### ISSUE THREAD

**Issue by meduza777** [miloschuman/yii2-highcharts#77]
In browsers' web console i get highcharts error 16, when i want to use highstock with
HighchartsAsset::register($this)->withScripts(['highstock']);

both highcharts.js highstock.js scripts is used by page. 
however highcharts.js should not be registered if highstock,js is used [https://www.highcharts.com/errors/16/](https://www.highcharts.com/errors/16/)

problem is in src/HighchartsAsset.php
line
        // make sure the highcharts base file is included first
        array_unshift($this->js, "highcharts.$ext"

**Comment by miloschuman** [comment]
Try using `'modules/stock'` instead of `'highstock'`.
```php
HighchartsAsset::register($this)->withScripts(['modules/stock']);
```
To reduce potential conflicts, I started using highcharts new module pattern for imports, but I forgot to update the README file to reflect that.

**Comment by miloschuman** [comment]
Updated README to reflect new usage.
