### ISSUE TITLE
The file or directory to be published does not exist:

### ISSUE THREAD

**Issue by fasi1208** [miloschuman/yii2-highcharts#82]
I have installed the `highcharts` package in my project. Now I am trying to view a sample chart but I am getting an error.

`use miloschuman\highcharts\Highcharts;
 <?=
  Highcharts::widget([
      'options' => [
          'title' => ['text' => 'Fruit Consumption'],
          'xAxis' => [
              'categories' => ['Apples', 'Bananas', 'Oranges']
          ],
          'yAxis' => [
              'title' => ['text' => 'Fruit eaten']
          ],
          'series' => [
              ['name' => 'Jane', 'data' => [1, 0, 4]],
              ['name' => 'John', 'data' => [5, 7, 3]]
          ]
      ]
  ]);
  ?>`

**Error**

`Invalid Argument – yii\base\InvalidArgumentException
The file or directory to be published does not exist: F:\xampp\htdocs\mdc/vendor\bower/highcharts`

**Comment by miloschuman** [comment]
Fixed in v10.0.1.
