### ISSUE TITLE
error install library via composer

### ISSUE THREAD

**Issue by tallot13** [miloschuman/yii2-highcharts#85]
composer require miloschuman/yii2-highcharts-widget
Using version ^8.0 for miloschuman/yii2-highcharts-widget
./composer.json has been created
Running composer update miloschuman/yii2-highcharts-widget
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires miloschuman/yii2-highcharts-widget ^8.0 -> satisfiable by miloschuman/yii2-highcharts-widget[v8.0].
    - miloschuman/yii2-highcharts-widget v8.0 requires bower-asset/highcharts ^8.0 -> could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, deleting ./composer.json.

**Comment by miloschuman** [comment]
You will need to use either **asset-packagist** or **fxp/composer-asset-plugin**. See here for instructions:
https://www.yiiframework.com/doc/guide/2.0/en/structure-assets#bower-npm-assets
